import os
os.system("clear")
import time
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print("Oi mae :)")
print(" ")
time.sleep(1.0)
print("Eu sei que...")
print(" ")
time.sleep(1.0)
print("Nao tenho sido um bom filho")
print(" ")
time.sleep(1.0)
print("Nos ultimos dias...")
print(" ")
time.sleep(1.0)
print("E quero te pedir desculpa...")
print(" ")
time.sleep(1.0)
print("E q nos ultimos anos n tem sido facil pra mim")
print(" ")
time.sleep(1.0)
print("E que eu prometo melhorar...")
print(" ")
time.sleep(1.0)
print("Saiba que Te Amo <3")
print(" ")
time.sleep(1.0)
print("E muito...")
print(" ")
time.sleep(1.0)
print("Beijos")
print(" ")
time.sleep(1.0)
